# Generated by Django 3.2.7 on 2021-10-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biofloc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build_tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanks', models.IntegerField()),
                ('water', models.IntegerField()),
                ('fish', models.IntegerField()),
                ('food', models.IntegerField()),
            ],
        ),
    ]
