# Generated by Django 2.0 on 2021-08-29 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('problem', models.CharField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='account.Profile')),
                ('fisheries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
